export default [
   {pid : 101  ,name : "Mango",       price : 100 , image : "img/mango.webp"},
   {pid : 102  ,name : "Mango" ,      price : 150 , image : "img/mango2.jpg"},
   {pid : 103  ,name : "Grape" ,      price : 100 , image:  "img/grape.jpg"},
   {pid : 104  ,name : "BlackGrape",  price : 120 , image : "img/blackGrape.jpg"},
   {pid : 105  ,name : "Banana" ,     price : 80 ,  image : "img/banana.jpg"},
   {pid : 106  ,name : "Cherry" ,     price : 180 , image : "img/cherry.jpg"},
   {pid : 107  ,name : "Pineapple",   price : 200 , image : "img/pineapple.jpg"},
   {pid : 108  ,name : "pomegrante" , price : 230 , image : "img/pomegrante.jpg"},
   {pid : 109  ,name : "Papaya" ,     price : 160 , image : "img/papaya.jpg"},
   {pid : 110  ,name : "Orange" ,     price : 230 , image : "img/orange.jpg"},
   {pid : 111  ,name : "Kiwi",        price : 300 , image : "img/kiwi.jpg"},
   {pid : 112  ,name : "Carrot",      price : 150,  image : "img/carrot.jpg"},

   {pid : 113  ,name : "coriander",   price : 80,   image : "img/coriander.jpg"},
   {pid : 114  ,name : "Curry Leaves",price : 70,   image : "img/curryLeaves.jpg"},
   {pid : 115  ,name : "Garlic",      price : 200 , image : "img/garlic.jpg"},
   {pid : 116  ,name : "Ginger",      price : 250 , image : "img/ginger.jpg"},
   {pid : 117  ,name : "Okra",        price : 350,  image : "img/okra.jpg"},
   {pid : 118  ,name : "Onion" ,      price : 390 , image : "img/onion.png"},
   {pid : 119  ,name : "Peas" ,      price : 400,  image : "img/peas.jpg"},
   {pid : 120  ,name : " Potato",    price :200,   image :"img/potato.jpg"},
   {pid : 121  ,name : "Spinch",      price: 150,  image :"img/spinch.jpg"},

   {pid : 122  ,name : "Amul Butter", price : 450 ,  image : "img/amul butter.jpg"},
   {pid : 123  ,name : "Amul Cheese", price : 430,   image : "img/amulCheese.jpg"},
   {pid : 124  ,name : "Chhachh" ,    price : 1000 , image : "img/chhachh.webp"},
   {pid : 125  ,name : "Dahi",        price : 180,   image : "img/dahi.webp"},
   {pid : 126  ,name : "Milk",        price : 180,   image : "img/milk.jpg"},
   {pid : 127  ,name : "Mazza" ,      price : 200 ,  image : "img/mazza.webp"},
   {pid : 128  ,name : "paneer",      price : 500,   image : "img/paneer.jpg"}
]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         